//ADDITION ROUTE
POST https://api-nodejs-fastify-0gvn.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 03",
  "description": "Esse é o vídeo 03",
  "duration": 120
}

###
//ADDITION ROUTE
GET https://api-nodejs-fastify-0gvn.onrender.com/videos

###
//ADDITION ROUTE - QUERY PARAMS
//Posso utilizar o Query params para buscar coisas específicas
GET https://api-nodejs-fastify-0gvn.onrender.com/videos?search=01

###
//UPDATE ROUTE - BY ID
PUT https://api-nodejs-fastify-0gvn.onrender.com/videos/5c530c11-784a-446b-b9bc-7756ac1dc7ab
Content-Type: application/json

{
  "title": "Video atualizado",
  "description": "Esse é o video atualizado",
  "duration": 180
}

###
//DELETE ROUTE - BY ID
DELETE  https://api-nodejs-fastify-0gvn.onrender.com/videos/1b39f1f7-5884-42d0-9f8d-8c68f853cb7d