//ADDITION ROUTE
POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video JS",
  "description": "Esse é o video 01",
  "duration": 180
}

###
//ADDITION ROUTE
GET http://localhost:3333/videos

###
//ADDITION ROUTE - QUERY PARAMS
//Posso utilizar o Query params para buscar coisas específicas
GET http://localhost:3333/videos?search=node

###
//UPDATE ROUTE - BY ID
PUT http://localhost:3333/videos/5c530c11-784a-446b-b9bc-7756ac1dc7ab
Content-Type: application/json

{
  "title": "Video atualizado",
  "description": "Esse é o video atualizado",
  "duration": 180
}

###
//DELETE ROUTE - BY ID
DELETE  http://localhost:3333/videos/5c530c11-784a-446b-b9bc-7756ac1dc7ab