POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o video 01",
  "duration": 180
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/4ee49c0f-1625-4001-8605-a968dc39db3a
Content-Type: application/json

{
  "title": "Video atualizado",
  "description": "Esse é o video atualizado",
  "duration": 180
}

###
DELETE  http://localhost:3333/videos/4ee49c0f-1625-4001-8605-a968dc39db3a